# Site settings
title: Vivek Mahato
description: 'Business Card Page'
url: 'https://www.vivekmahato.com'
baseurl: ''
profilepic: '/images/vivekmahato.JPG'
bkimage: '/images/bg.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'e3b1c68a0d.js'

author:
  name: 'Dr. Vivek Mahato, PhD'
  email: vivekmahato@live.com
  twitter_username: mistermahato
#  facebook_username: joshgerdes
  github_username:  vivekmahato
  linkedin_username:  vivek-mahato

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
